name: Run Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
    - run: yarn
    - run: yarn test

  approve:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Approve
      uses: "peter-evans/approval-action@v2.1.0"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        message: "Unit tests passed"
